# This file serves for generating the OptaPlanner documentation website.
# For local development, see antora-playbook-author.yml.
site:
  title: Documentation
  url: https://www.optaplanner.org/docs
  start_page: optaplanner::planner-introduction/planner-introduction.adoc
  robots: allow
  keys:
    google_analytics: 'UA-39485370-1'
content:
  edit_url: '{web_url}/edit/main/{path}'
  sources:
    - url: git@github.com:kiegroup/optaplanner.git
      # Update with every release.
      branches: [8.21.x]
      start_path: optaplanner-docs/src
ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
runtime:
  fetch: true
antora:
  extensions:
    - '@antora/lunr-extension'
